### ISSUE TITLE
Can't create new user

### ISSUE THREAD

**Issue by hermanguilliman** [Archef2000/ocserv#1]
I got an error "Cannot open '/config/ocpasswd.tmp' for writing." when create a new user

**Comment by archef2000** [comment]
Sorry my bad i did not update the docs for the setup you can just assign var:
USER_$N
PASS_$N
Where $N stands for a number between 1-10.
On startup it will always get written to the ocpasswd file if the user does not exist.

**Comment by archef2000** [comment]
Closed of inactivity.
